import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>"Blogs"</title>
        <meta name="description"  />
      </Head>
      <body className={inter.className}>
        <header>
          <h1>My Blog</h1>
          <nav>
            <ul>
              <li><Link href="/">Home</Link></li>
              <li><Link href="/about">About</Link></li>
              <li><Link href="/contact">Contact</Link></li>
            </ul>
          </nav>
        </header>

        {children}

        <footer>
          <p>&copy; 2023 My Blog</p>
        </footer>
      </body>
    </html>
  )
}
